#!/bin/bash

# Please change the INPUT_DIR to the directory which contains the data file
# generated by hydro codes
# Please change the OUTPUT_DIR to the directory which contains the VTK output file
INPUT_DIR=/home/james/HPC/finalProject/vwwriter/density_in/
OUTPUT_DIR=/home/james/HPC/finalProject/vwwriter/density_out/
SUFFIX=.out
FILES=`ls -a $INPUT_DIR`

for file in $FILES
do
    if [ $file != "." ] && [ $file != ".." ]; then
        in_file=$INPUT_DIR$file
        out_file=$OUTPUT_DIR$file$SUFFIX
        echo "$in_file"
        echo "$out_file"
        vwcurve $in_file $out_file
    fi
done
